\i schema.sql
\i new_data/Departments.sql
\i new_data/MeetingRooms.sql
\i new_data/Employees.sql
\i new_data/Booker.sql
\i new_data/Manager.sql
\i new_data/HealthDeclaration.sql
\i new_data/Sessions.sql
\i new_data/Joins.sql
\i new_data/Updates.sql
\i function/core.sql
\i function/health.sql
\i function/basic.sql
\i function/check.sql
\i function/trigger.sql
\i function/Admin.sql
